### PR TITLE
1. fix the dead loop when slave blocked by election campaign

### PR DESCRIPTION
**Pull request by greatsharp**
2. controller resume and suspend cluster checker
3. use gopkg.in/yaml.v3

### CODE REVIEW

**Comment by torwig** [comment]
@greatsharp You can run `go mod tidy` (if you didn't) after upgrading the dependency.

**Comment by greatsharp** [comment]
> @greatsharp You can run `go mod tidy` (if you didn't) after upgrading the dependency.

done, thanks for your remention

**Comment by greatsharp** [comment]
1. test the case  of delete the lease from etcd side.
2. test the case of delete the leader key from etcd side.
3. test the case of shutdown etcd.

**Comment by git-hulk** [comment]
@greatsharp Is this PR ready to review?

**Pull request closed without merging**
