### PR TITLE
Add UI

### PR DESCRIPTION
**Pull request by Venjy**
image
image
image
image
image

This is partial implementation of #86

### CODE REVIEW

**Comment by Venjy** [comment]
@git-hulk Could you please take a look about the CI failure? Seems related to a base package from go.

**Comment by git-hulk** [comment]
> @git-hulk Could you please take a look about the CI failure? Seems related to a base package from go.

No indeed, it's caused by using the deprecated API in Go1.19.

**Comment by Venjy** [comment]
Did some optimization: 
- Move namespace creation button to upper right corner
- Provide a button to creat namespace when user doesn't select any namespace
- Turn the side menu bar into two layers

screen recording

@git-hulk Please take a look

**Comment by aleksraiden** [comment]
Awesome, @Venjy

**Comment by git-hulk** [comment]
Close it due to lack of active, feel free to follow up if you come back.

**Pull request closed without merging**
