### PR TITLE
Add NOTICE file for the controller server

### PR DESCRIPTION
**Pull request by git-hulk**
As the title mentioned, this PR adds the NOTICE file for the controller dependencies.

### CODE REVIEW

**Comment by git-hulk** [comment]
It will be better to use the script to generate NOTICE and its license file automatically.

**Review by torwig — APPROVED** [review]

**Review by PragmaTwice — APPROVED** [review]

**Comment by PragmaTwice** [comment]
```
	github.com/gin-gonic/gin v1.9.1 x
	github.com/go-playground/validator/v10 v10.14.0
	github.com/go-redis/redis/v8 v8.11.5 x
	github.com/go-resty/resty/v2 v2.12.0
	github.com/go-zookeeper/zk v1.0.3 x
	github.com/olekukonko/tablewriter v0.0.5 x
	github.com/prometheus/client_golang v1.11.1 x
	github.com/spf13/cobra v1.8.0 x
	github.com/stretchr/testify v1.8.3 x
	go.etcd.io/etcd v3.3.27+incompatible x
	go.etcd.io/etcd/client/v3 v3.5.4 x
	go.uber.org/atomic v1.7.0 x
	go.uber.org/zap v1.21.0 x
	gopkg.in/yaml.v1 v1.0.0-20140924161607-9f9df34309c0 x
```
seems licenses for `github.com/go-playground/validator/v10`, `github.com/go-resty/resty/v2` is missing..

**Review by PragmaTwice — CHANGES_REQUESTED** [review]
See above.

**Comment by git-hulk** [comment]
> seems licenses for github.com/go-playground/validator/v10, github.com/go-resty/resty/v2 is missing..

@PragmaTwice Yes, those two are missed. I have added them, please take a look again.

**Review by torwig — APPROVED** [review]

**Review by PragmaTwice — APPROVED** [review]

**Pull request merged**
