### PR TITLE
Introduce etcd's raft to implement the KV store

### PR DESCRIPTION
**Pull request by git-hulk**
Currently, the controller must depend on the external service like zookeeper/etcd to store its data. And it's not so friendly for users since they need to setup another cluster before running the controller server. To make this process simple, we would like to introduce the raft engine to save and replicate the data.

### CODE REVIEW

**Comment by git-hulk** [comment]
This PR is generally ready to be reviewed. Will add more integration test cases with the raft engine in another PRs when I get time.

**Review by PragmaTwice — APPROVED** [review]
Great!

**Comment by PragmaTwice** [comment]
Maybe we can consider to release 1.1.0 (or 2.0.0?) after this?

**Comment by git-hulk** [comment]
> Maybe we can consider to release 1.1.0 (or 2.0.0?) after this?

Okay, will also try to resolve significant problems in issues before the next release 1.1.0.

**Comment by greatsharp** [comment]
good job, waiting for new release

**Comment by git-hulk** [comment]
@greatsharp Expect to release this feature before 2025.

**Pull request merged**
