### PR TITLE
Implement the node management, import cluster, migrate slot UI for Kvrocks controller

### PR DESCRIPTION
**Pull request by CulturalProfessor**
#### Description

This PR introduces UI for managing nodes, importing clusters and migrating slots. 
#### Screencast

Here is a video demonstration of the node dashboard

[Screencast from 30-09-24 10:06:54 PM IST.webm](https://github.com/user-attachments/assets/182bdd3e-a64b-460a-9d8e-2ee6564b957e)

### CODE REVIEW

**Comment by CulturalProfessor** [comment]
Import Cluster Feature

[Screencast from 30-09-24 08:24:42 PM IST.webm](https://github.com/user-attachments/assets/c4c63491-6299-4405-92ad-b81aea4c8d7a)

**Comment by CulturalProfessor** [comment]
Migrate Slot Feature

[Screencast from 30-09-24 09:40:34 PM IST.webm](https://github.com/user-attachments/assets/e92a5494-2f7a-4a41-96bf-de67a22c52b1)

**Comment by CulturalProfessor** [comment]
Guys please review @jihuayu @git-hulk !

**Review by jihuayu — APPROVED** [review]

**Comment by mansoncui** [comment]
How to import kvrocks cluster files or examples into kvctl?

**Pull request merged**
