### PR TITLE
Implement the shard management UI for Kvrocks controller

### PR DESCRIPTION
**Pull request by CulturalProfessor**
#### Description

This PR introduces UI for managing shards, including the feature to create and delete shards based upon previous cluster ui. The following features and improvements are included:

- [x] **Shard Sidebar Component** listing all shards.
- [x] **Shard Card Component** listing all nodes data.
- [x] **Shard Create Component** for creating shards.
- [x] **Loading Component** for adding spinner while loading data.

#### Screencast

Here is a video demonstration of the new UI features for creating and deleting shards:

https://www.loom.com/share/ce0caaac946b46fa95bbb44c66324488?sid=ab77ae3e-8c4a-4ef5-b950-9447003927a7

### CODE REVIEW

**Comment by CulturalProfessor** [comment]
@git-hulk @jihuayu guys please review !

**Comment by jihuayu** [comment]
Great! I will have a look today!

**Review by jihuayu — APPROVED** [review]
Great! Thank you!

**Comment by jihuayu** [comment]
Can you list out the issues you have completed? @CulturalProfessor 
https://github.com/apache/kvrocks-controller/issues/135

**Pull request merged**
