### PR TITLE
Avoid creating too many Redis clients by reusing

### LINKED ISSUE #186: Too many redis session will created in parallelProbeNodes func
When a function is called, the ClusterNode is inconsistent every time.Will create a lot of session.
https://github.com/apache/kvrocks-controller/blob/3a336a9b88faaef3678f2cfcdf81f67ae23d9d14/store/cluster_node.go#L143

### PR DESCRIPTION
**Pull request by erwadba**
fix #186
Using map to store redis session

### CODE REVIEW

**Comment by erwadba** [comment]
cc @git-hulk

**Comment by git-hulk** [comment]
@erwadba Thanks for your contribution.

**Review by git-hulk — APPROVED** [review]

**Comment by git-hulk** [comment]
@erwadba Would you mind fixing the lint error?

**Comment by erwadba** [comment]
> @erwadba Would you mind fixing the lint error?

done.

**Comment by git-hulk** [comment]
@erwadba No worry about this error, it’s not related to this PR. I will merge this PR after fixing it.

**Review by git-hulk — APPROVED** [review]
LGTM

**Comment by erwadba** [comment]
https://github.com/apache/kvrocks-controller/blob/3a336a9b88faaef3678f2cfcdf81f67ae23d9d14/store/cluster.go#L48-L54
https://github.com/apache/kvrocks-controller/blob/3a336a9b88faaef3678f2cfcdf81f67ae23d9d14/controller/controller_test.go#L35-L40
Does --replica 1 means one node in kvrocks cluter? It doesn't look like redis --replica 1 means 2 node

**Comment by git-hulk** [comment]
> @erwadba No worry about this error, it’s not related to this PR. I will merge this PR after fixing it.

Would be fixed in PR: https://github.com/apache/kvrocks-controller/pull/188

**Comment by git-hulk** [comment]
> https://github.com/apache/kvrocks-controller/blob/3a336a9b88faaef3678f2cfcdf81f67ae23d9d14/store/cluster.go#L48-L54
> 
> 
> https://github.com/apache/kvrocks-controller/blob/3a336a9b88faaef3678f2cfcdf81f67ae23d9d14/controller/controller_test.go#L35-L40
> 
> 
> Does --replica 1 means one node in kvrocks cluter? It doesn't look like redis --replica 1 means 2 node

Yes, --replica 1 means only one replica(master only).

**Pull request merged**
