### PR TITLE
Add UI

### PR DESCRIPTION
**Pull request by Venjy**
4481684332935_ pic
4491684332966_ pic
4501684332985_ pic
4521684333025_ pic
4511684333006_ pic

### CODE REVIEW

**Comment by Venjy** [comment]
CI not passed for 3 times.
First time is a really issue, fixed in [this commit](https://github.com/RocksLabs/kvrocks_controller/pull/64/commits/c48fb2829e12fdc89d84281bdae8b59f2aaff2cc).
The second time and third time reports error during run `npm run build`. I cannot reproduce in my local (with node 12/14/18), and first time there's no issue in that step. So I doubt that because of npm cache issue.

**Comment by Venjy** [comment]
Tested CI in [this branch](https://github.com/Venjy/kvrocks_controller/commits/unstable-test-ci), passed.
So I am more inclined to be that the cache of the CI that failed to run before caused the subsequent failure.

**Comment by git-hulk** [comment]
Hi @Venjy 

Can you help to fix the build error in CI?

**Comment by Venjy** [comment]
@git-hulk I think the CI broken is because of cache issue during make step, will try to create a new PR to re-trigger CI with a new enrionment.

**Pull request closed without merging**
